
export const BIBLE_BOOKS = [
  { code: 'GEN', chapters: 50, name: 'Genesis' },
  { code: 'EXO', chapters: 40, name: 'Exodus' },
  { code: 'LEV', chapters: 27, name: 'Leviticus' },
  { code: 'NUM', chapters: 36, name: 'Numbers' },
  { code: 'DEU', chapters: 34, name: 'Deuteronomy' },
  { code: 'JOS', chapters: 24, name: 'Joshua' },
  { code: 'JDG', chapters: 21, name: 'Judges' },
  { code: 'RUT', chapters: 4, name: 'Ruth' },
  { code: '1SA', chapters: 31, name: '1 Samuel' },
  { code: '2SA', chapters: 24, name: '2 Samuel' },
  { code: '1KI', chapters: 22, name: '1 Kings' },
  { code: '2KI', chapters: 25, name: '2 Kings' },
  { code: '1CH', chapters: 29, name: '1 Chronicles' },
  { code: '2CH', chapters: 36, name: '2 Chronicles' },
  { code: 'EZR', chapters: 10, name: 'Ezra' },
  { code: 'NEH', chapters: 13, name: 'Nehemiah' },
  { code: 'EST', chapters: 10, name: 'Esther' },
  { code: 'JOB', chapters: 42, name: 'Job' },
  { code: 'PSA', chapters: 150, name: 'Psalms' },
  { code: 'PRO', chapters: 31, name: 'Proverbs' },
  { code: 'ECC', chapters: 12, name: 'Ecclesiastes' },
  { code: 'SNG', chapters: 8, name: 'Song of Solomon' },
  { code: 'ISA', chapters: 66, name: 'Isaiah' },
  { code: 'JER', chapters: 52, name: 'Jeremiah' },
  { code: 'LAM', chapters: 5, name: 'Lamentations' },
  { code: 'EZK', chapters: 48, name: 'Ezekiel' },
  { code: 'DAN', chapters: 12, name: 'Daniel' },
  { code: 'HOS', chapters: 14, name: 'Hosea' },
  { code: 'JOE', chapters: 3, name: 'Joel' },
  { code: 'AMO', chapters: 9, name: 'Amos' },
  { code: 'OBD', chapters: 1, name: 'Obadiah' },
  { code: 'JON', chapters: 4, name: 'Jonah' },
  { code: 'MIC', chapters: 7, name: 'Micah' },
  { code: 'NAM', chapters: 3, name: 'Nahum' },
  { code: 'HAB', chapters: 3, name: 'Habakkuk' },
  { code: 'ZEP', chapters: 3, name: 'Zephaniah' },
  { code: 'HAG', chapters: 2, name: 'Haggai' },
  { code: 'ZEC', chapters: 14, name: 'Zechariah' },
  { code: 'MAL', chapters: 4, name: 'Malachi' },
  { code: 'MAT', chapters: 28, name: 'Matthew' },
  { code: 'MRK', chapters: 16, name: 'Mark' },
  { code: 'LUK', chapters: 24, name: 'Luke' },
  { code: 'JHN', chapters: 21, name: 'John' },
  { code: 'ACT', chapters: 28, name: 'Acts' },
  { code: 'ROM', chapters: 16, name: 'Romans' },
  { code: '1CO', chapters: 16, name: '1 Corinthians' },
  { code: '2CO', chapters: 13, name: '2 Corinthians' },
  { code: 'GAL', chapters: 6, name: 'Galatians' },
  { code: 'EPH', chapters: 6, name: 'Ephesians' },
  { code: 'PHP', chapters: 4, name: 'Philippians' },
  { code: 'COL', chapters: 4, name: 'Colossians' },
  { code: '1TH', chapters: 5, name: '1 Thessalonians' },
  { code: '2TH', chapters: 3, name: '2 Thessalonians' },
  { code: '1TI', chapters: 6, name: '1 Timothy' },
  { code: '2TI', chapters: 4, name: '2 Timothy' },
  { code: 'TIT', chapters: 3, name: 'Titus' },
  { code: 'PHM', chapters: 1, name: 'Philemon' },
  { code: 'HEB', chapters: 13, name: 'Hebrews' },
  { code: 'JAS', chapters: 5, name: 'James' },
  { code: '1PE', chapters: 5, name: '1 Peter' },
  { code: '2PE', chapters: 3, name: '2 Peter' },
  { code: '1JN', chapters: 5, name: '1 John' },
  { code: '2JN', chapters: 1, name: '2 John' },
  { code: '3JN', chapters: 1, name: '3 John' },
  { code: 'JUD', chapters: 1, name: 'Jude' },
  { code: 'REV', chapters: 22, name: 'Revelation' }
];
