export const GREEK_BOOKS = [
  { id: 'Mt', name: 'Matthew' },
  { id: 'Mk', name: 'Mark' },
  { id: 'Lk', name: 'Luke' },
  { id: 'Jn', name: 'John' },
  { id: 'Ac', name: 'Acts' },
  { id: 'Ro', name: 'Romans' },
  { id: '1Co', name: '1 Corinthians' },
  { id: '2Co', name: '2 Corinthians' },
  { id: 'Ga', name: 'Galatians' },
  { id: 'Eph', name: 'Ephesians' },
  { id: 'Php', name: 'Philippians' },
  { id: 'Col', name: 'Colossians' },
  { id: '1Th', name: '1 Thessalonians' },
  { id: '2Th', name: '2 Thessalonians' },
  { id: '1Ti', name: '1 Timothy' },
  { id: '2Ti', name: '2 Timothy' },
  { id: 'Tit', name: 'Titus' },
  { id: 'Phm', name: 'Philemon' },
  { id: 'Heb', name: 'Hebrews' },
  { id: 'Jas', name: 'James' },
  { id: '1Pe', name: '1 Peter' },
  { id: '2Pe', name: '2 Peter' },
  { id: '1Jn', name: '1 John' },
  { id: '2Jn', name: '2 John' },
  { id: '3Jn', name: '3 John' },
  { id: 'Jud', name: 'Jude' },
  { id: 'Re', name: 'Revelation' }
];
